# Starter pipeline
- task: DotNetCoreCLI@2
  displayName: &#39;Publish the project - Release&#39;
  inputs:
    command: &#39;publish&#39;
    projects: &#39;**/*.csproj&#39;
    publishWebProjects: false
    arguments: &#39;--no-build --configuration Release --output $(Build.ArtifactStagingDirectory)/Release&#39;
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: &#39;Publish Artifact: drop&#39;
  condition: succeeded()
